// src/components/FundsTable.vue
<!-- src/components/FundsTable.vue -->
<template>
  <div class="card">
    <DataTable
      :value="funds"
      :expandedRows="expandedRows"
      @row-expand="onRowExpand"
      @row-collapse="onRowCollapse"
      dataKey="isin"
      class="p-datatable-sm"
      :paginator="true"
      :rows="20"
      :rowsPerPageOptions="[10, 20, 50]"
      paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
      :filters="filters"
      filterDisplay="menu"
      v-model:filters="filters"
      sortField="name"
      :sortOrder="1"
    >
      <Column expander style="width: 40px" />
      <Column field="name" header="Fund Name" :sortable="true" style="min-width: 300px">
        <template #body="slotProps">
          <div class="flex flex-column">
            <span class="font-medium">{{ slotProps.data.name }}</span>
          </div>
        </template>
      </Column>
      <Column field="category" header="Category" :sortable="true" style="width: 200px">
        <template #body="slotProps">
          <Tag :value="slotProps.data.category" />
        </template>
      </Column>
      <Column field="portfolioCount" header="Portfolios" style="width: 120px" :sortable="true">
        <template #body="slotProps">
          <div class="flex align-items-center justify-content-end gap-2">
            <i class="pi pi-users text-gray-500" />
            <span>{{ portfolioCounts[slotProps.data.isin] || 0 }}</span>
          </div>
        </template>
        <template #sortable="slotProps">
          {{ portfolioCounts[slotProps.data.isin] || 0 }}
        </template>
      </Column>
      
      <template #expansion="slotProps">
        <div class="p-4 bg-gray-50">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 class="text-lg font-semibold mb-4">Performance Metrics</h3>
              <div class="grid grid-cols-3 gap-4">
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">3M Return</p>
                  <PerformanceBadge :value="parseFloat(slotProps.data.performance?.threeMonthChange)" />
                </div>
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">1Y Return</p>
                  <PerformanceBadge :value="parseFloat(slotProps.data.performance?.oneYearChange)" />
                </div>
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">3Y Return</p>
                  <PerformanceBadge :value="parseFloat(slotProps.data.performance?.threeYearChange)" />
                </div>
              </div>
            </div>
            <div>
              <h3 class="text-lg font-semibold mb-4">Asset Allocation</h3>
              <div class="grid grid-cols-3 gap-4">
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">UK Bonds</p>
                  <span class="font-medium">{{ formatPercentage(slotProps.data.allocation?.ukBond) }}</span>
                </div>
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">Non-UK Bonds</p>
                  <span class="font-medium">{{ formatPercentage(slotProps.data.allocation?.nonUKBond) }}</span>
                </div>
                <div class="bg-white p-3 rounded-lg shadow-sm">
                  <p class="text-sm text-gray-600 mb-2">Cash</p>
                  <span class="font-medium">{{ formatPercentage(slotProps.data.allocation?.cash) }}</span>
                </div>
              </div>
            </div>
          </div>
          <div class="mt-4 pt-4 border-t border-gray-200">
            <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2">
              <div class="flex items-center gap-3">
                <a 
                  :href="slotProps.data.links?.ft" 
                  target="_blank" 
                  class="text-blue-600 hover:text-blue-800 inline-flex items-center gap-1"
                >
                  <i class="pi pi-external-link"></i>
                  <span>View on Financial Times</span>
                </a>
                <span class="text-sm text-gray-500">ISIN: {{ slotProps.data.isin }}</span>
              </div>
              <div class="text-sm text-gray-500">
                Last Updated: {{ formatDate(slotProps.data.lastUpdated) }}
              </div>
            </div>
          </div>
        </div>
      </template>
    </DataTable>
  </div>
</template>

<script>
import { ref, computed } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Tag from 'primevue/tag';
import PerformanceBadge from './PerformanceBadge.vue';

const formatPercentage = (value) => {
  if (value === undefined || value === null) return 'N/A';
  return value >= 0 ? `+${value.toFixed(2)}%` : `${value.toFixed(2)}%`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

export default {
  name: 'FundsTable',
  components: {
    DataTable,
    Column,
    Tag,
    PerformanceBadge
  },
  props: {
    funds: {
      type: Array,
      required: true
    },
    portfolioCounts: {
      type: Object,
      required: true
    }
  },
  setup() {
    const expandedRows = ref({});
    const filters = ref({});

    const onRowExpand = (event) => {
      expandedRows.value[event.data.isin] = true;
    };

    const onRowCollapse = (event) => {
      delete expandedRows.value[event.data.isin];
    };

    return {
      expandedRows,
      filters,
      onRowExpand,
      onRowCollapse,
      formatPercentage,
      formatDate
    };
  }
};
</script>

<style>
.p-datatable .p-datatable-tbody > tr > td {
  padding: 0.75rem 1rem;
}

.p-datatable .p-datatable-thead > tr > th {
  background-color: #f8fafc;
  border-bottom: 2px solid #e2e8f0;
  font-weight: 600;
  color: #475569;
}
</style>

// src/components/FundsTable.jsx
import React, { useState } from 'react';
import {
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Link,
  Box,
  Text,
  Badge,
  Flex,
  Icon,
  Tooltip,
  Collapse,
  HStack,
  VStack,
  Divider
} from '@chakra-ui/react';
import { 
  FiExternalLink, 
  FiChevronDown, 
  FiChevronRight, 
  FiTrendingUp, 
  FiTrendingDown,
  FiUsers
} from 'react-icons/fi';

const formatPercentage = (value) => {
  if (value === undefined || value === null) return 'N/A';
  const formatted = value.toFixed(2);
  return `${formatted}%`;
};

const PerformanceBadge = ({ value }) => {
  if (value === undefined || value === null) return 'N/A';
  
  const color = value >= 0 ? 'green' : 'red';
  const icon = value >= 0 ? FiTrendingUp : FiTrendingDown;
  
  return (
    <Badge colorScheme={color} display="flex" alignItems="center" gap={1}>
      <Icon as={icon} />
      {formatPercentage(value)}
    </Badge>
  );
};

const ExpandedRow = ({ fund }) => {
  return (
    <Box p={4} bg="gray.50">
      <VStack align="stretch" spacing={4}>
        <HStack justify="space-between">
          <Text fontWeight="bold">Performance Metrics</Text>
          <Text fontSize="sm" color="gray.600">Last Updated: {new Date(fund.lastUpdated).toLocaleDateString()}</Text>
        </HStack>
        <Flex gap={6}>
          <VStack align="start">
            <Text fontSize="sm" color="gray.600">3 Month Change</Text>
            <PerformanceBadge value={fund.performance?.threeMonthChange} />
          </VStack>
          <VStack align="start">
            <Text fontSize="sm" color="gray.600">1 Year Change</Text>
            <PerformanceBadge value={fund.performance?.oneYearChange} />
          </VStack>
          <VStack align="start">
            <Text fontSize="sm" color="gray.600">3 Year Change</Text>
            <PerformanceBadge value={fund.performance?.threeYearChange} />
          </VStack>
        </Flex>
        <Divider />
        <Box>
          <Text fontWeight="bold" mb={2}>Asset Allocation</Text>
          <HStack spacing={6}>
            <VStack align="start">
              <Text fontSize="sm" color="gray.600">UK Bonds</Text>
              <Text>{formatPercentage(fund.allocation?.ukBond)}</Text>
            </VStack>
            <VStack align="start">
              <Text fontSize="sm" color="gray.600">Non-UK Bonds</Text>
              <Text>{formatPercentage(fund.allocation?.nonUKBond)}</Text>
            </VStack>
            <VStack align="start">
              <Text fontSize="sm" color="gray.600">Cash</Text>
              <Text>{formatPercentage(fund.allocation?.cash)}</Text>
            </VStack>
          </HStack>
        </Box>
      </VStack>
    </Box>
  );
};

const FundsTable = ({ funds, portfolioCounts }) => {
  const [expandedRows, setExpandedRows] = useState(new Set());

  const toggleRow = (isin) => {
    const newExpandedRows = new Set(expandedRows);
    if (newExpandedRows.has(isin)) {
      newExpandedRows.delete(isin);
    } else {
      newExpandedRows.add(isin);
    }
    setExpandedRows(newExpandedRows);
  };

  return (
    <Box overflowX="auto" shadow="md" rounded="lg" bg="white">
      <Table variant="simple">
        <Thead bg="gray.50">
          <Tr>
            <Th width="40px"></Th>
            <Th>Fund Name</Th>
            <Th>SEDOL</Th>
            <Th>Category</Th>
            <Th isNumeric>Client Portfolios</Th>
          </Tr>
        </Thead>
        <Tbody>
          {funds.map((fund) => (
            <React.Fragment key={fund.isin}>
              <Tr 
                cursor="pointer" 
                onClick={() => toggleRow(fund.isin)}
                _hover={{ bg: 'gray.50' }}
              >
                <Td>
                  <Icon 
                    as={expandedRows.has(fund.isin) ? FiChevronDown : FiChevronRight}
                    color="gray.500"
                  />
                </Td>
                <Td>
                  <Text fontWeight="medium">{fund.name}</Text>
                </Td>
                <Td>
                  <Text color="gray.600">{fund.sedol}</Text>
                </Td>
                <Td>
                  <Badge colorScheme="blue" variant="subtle">
                    {fund.category}
                  </Badge>
                </Td>
                <Td isNumeric>
                  <HStack justify="flex-end" spacing={1}>
                    <Icon as={FiUsers} color="gray.500" />
                    <Text>{portfolioCounts[fund.isin] || 0}</Text>
                  </HStack>
                </Td>
              </Tr>
              <Tr>
                <Td colSpan={5} p={0}>
                  <Collapse in={expandedRows.has(fund.isin)}>
                    <ExpandedRow fund={fund} />
                  </Collapse>
                </Td>
              </Tr>
            </React.Fragment>
          ))}
        </Tbody>
      </Table>
    </Box>
  );
};

export default FundsTable;
